### Runs the message generator tests in parallel without gathering coverage data

name: Interoperability tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  message-generator-test:
    name: MG Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75
          override: true
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          #save-if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}

      - name: Run bad-pool-config-test
        run: sh ./test/message-generator/test/bad-pool-config-test/bad-pool-config-test.sh

#      - name: Run interop-jd-translator
#        run: sh ./test/message-generator/test/interop-jd-translator/interop-jd-translator.sh
#
#        #- name: Run interop-jdc-change-upstream
#        #  run: sh ./test/message-generator/test/interop-jdc-change-upstream/interop-jdc-change-upstream.sh
#
#      - name: Run interop-proxy-with-multi-ups
#        run: sh ./test/message-generator/test/interop-proxy-with-multi-ups/interop-proxy-with-multi-ups.sh
#
#      - name: Run interop-proxy-with-multi-ups-extended
#        run: sh ./test/message-generator/test/interop-proxy-with-multi-ups-extended/interop-proxy-with-multi-ups-extended.sh
#
#      - name: Run jds-do-not-fail-on-wrong-tsdatasucc
#        run: sh ./test/message-generator/test/jds-do-not-fail-on-wrong-tsdatasucc/jds-do-not-fail-on-wrong-tsdatasucc.sh
#
#      - name: Run jds-do-not-panic-if-jdc-close-connection
#        run: sh ./test/message-generator/test/jds-do-not-panic-if-jdc-close-connection/jds-do-not-panic-if-jdc-close-connection.sh
#
#      - name: Run jds-do-not-stackoverflow-when-no-token
#        run: sh ./test/message-generator/test/jds-do-not-stackoverflow-when-no-token/jds-do-not-stackoverflow-when-no-token.sh
#
#      - name: Run pool-sri-test-1-standard
#        run: sh ./test/message-generator/test/pool-sri-test-1-standard/pool-sri-test-1-standard.sh
#
#      - name: Run pool-sri-test-close-channel
#        run: sh ./test/message-generator/test/pool-sri-test-close-channel/pool-sri-test-close-channel.sh
#
#      - name: Run pool-sri-test-extended_0
#        run: sh ./test/message-generator/test/pool-sri-test-extended_0/pool-sri-test-extended_0.sh
#
#      - name: Run pool-sri-test-extended_1
#        run: sh ./test/message-generator/test/pool-sri-test-extended_1/pool-sri-test-extended_1.sh
#
#      - name: Run pool-sri-test-reject-auth
#        run: sh ./test/message-generator/test/pool-sri-test-reject-auth/pool-sri-test-reject-auth.sh
#
#      - name: Run standard-coverage
#        run: sh ./test/message-generator/test/standard-coverage-test/standard-coverage-test.sh
#
#      - name: Run sv1-test
#        run: sh ./test/message-generator/test/sv1-test/sv1-test.sh
#
#      - name: Run translation-proxy-broke-pool
#        run: sh ./test/message-generator/test/translation-proxy-broke-pool/translation-proxy-broke-pool.sh
#
#      - name: Run translation-proxy
#        run: sh ./test/message-generator/test/translation-proxy/translation-proxy.sh
#
#      - name: Run translation-proxy-old-share
#        run: sh ./test/message-generator/test/translation-proxy-old-share/translation-proxy-old-share.sh
#
#      - name: Coverage report
#        run: sh ./scripts/code-coverage-report.sh
#
#      - name: Archive MG code coverage results
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage-report
#          path: 'target/*.xml'
#
#      - name: Archive log files
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: logs
#          path: './utils/message-generator/*.log'
#
#            # codecov:
#            #   needs: message-generator-test
#
#            #   name: Codecov Upload
#            #   runs-on: ubuntu-latest
#
#            #   steps:
#
#          #     - name: Checkout repository
#          #       uses: actions/checkout@v4
#
#          #     - name: Download all workflow run artifacts
#          #       uses: actions/download-artifact@v4
#
#          #     - name: Display structure of downloaded files
#          #       run: ls -R
#
#          #     - name: Upload to codecov.io
#          #       uses: codecov/codecov-action@v3
#          #       with:
#          #         files: coverage-report/*.xml, tarpaulin-report/*.xml
#          #         fail_ci_if_error: true
#          #         token: ${{ secrets.CODECOV_TOKEN }}
